#!/bin/bash
set -e

echo "Current user: $(whoami)"

if [ -f "Gemfile" ]; then
  bundle install
else
  echo "No Gemfile found, skipping dependencies installation."
fi

echo "Copying database.yml..."
cp -n config/database.yml.example config/database.yml

if [ -f "bin/rails" ]; then
  bin/rails db:prepare
else
  echo "bin/rails not found, skipping database."
fi

echo "Done!"
