#!/bin/bash

echo "Current user: $(whoami)"

if [ -f "Gemfile" ]; then
  bundle install
else
  echo "No Gemfile found, skipping dependencies installation."
fi

echo "Copying database.yml..."
cp --update=none config/database.yml.example config/database.yml

if [ -f "bin/rails" ]; then
  bin/rails db:prepare
  bin/rails tailwindcss:install
else
  echo "bin/rails not found, skipping database and tailwindcss preparation."
fi

echo "Done!"
